---
title: "Project 5: The War with Star Wars"
date: 2020-05-01T11:02:05+06:00
lastmod: 2020-09-15T10:42:26+06:00
weight: 5
draft: false
# search related keywords
keywords: [""]
---

### Walkthrough
```{=html}
<iframe id="kaltura_player" src="https://cdnapisec.kaltura.com/p/1157612/sp/115761200/embedIframeJs/uiconf_id/41338032/partner_id/1157612?iframeembed=true&playerId=kaltura_player&entry_id=1_c8g905uj&flashvars[localizationCode]=en&amp;flashvars[sideBarContainer.plugin]=true&amp;flashvars[sideBarContainer.position]=left&amp;flashvars[sideBarContainer.clickToClose]=true&amp;flashvars[chapters.plugin]=true&amp;flashvars[chapters.layout]=vertical&amp;flashvars[chapters.thumbnailRotator]=false&amp;flashvars[streamSelector.plugin]=true&amp;flashvars[EmbedPlayer.SpinnerTarget]=videoHolder&amp;flashvars[dualScreen.plugin]=true&amp;flashvars[Kaltura.addCrossoriginToIframe]=true&amp;&wid=1_8dqp37xp" width="608" height="402" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="W10 - Project 5 Walkthrough"></iframe>
```

### Background

Survey data is notoriously difficult to munge.  Even when the data is recorded cleanly the options for ‘write in questions’, ‘choose from multiple answers’, ‘pick all that are right’, and ‘multiple choice questions’ makes storing the data in a tidy format difficult.

In 2014, FiveThirtyEight surveyed over 1000 people to write the article titled, [America’s Favorite ‘Star Wars’ Movies (And Least Favorite Characters)](https://fivethirtyeight.com/features/americas-favorite-star-wars-movies-and-least-favorite-characters/). They have provided the data on [GitHub](https://github.com/fivethirtyeight/data/tree/master/star-wars-survey). 

For this project, your client would like to use the Star Wars survey data to figure out if they can predict an interviewing job candidate’s current income based on a few responses about Star Wars movies.  

### Client Request

The Client is who performed the survey but outsourced the analitics to a 3rd party. They want you to clean up the data so you can: 
    a. Validate the data provided on GitHub lines up with the article by recreating 2 of the visuals from the article
    a. Determine if you predict if a person from the survey makes more than $50k

### Data

__URL:__ [StarWars.csv](https://github.com/fivethirtyeight/data/raw/master/star-wars-survey/StarWars.csv)   
__Information:__ [Article](https://fivethirtyeight.com/features/americas-favorite-star-wars-movies-and-least-favorite-characters/)


### Readings
- [P4DS: CH6 Tidy Data](https://byuidatascience.github.io/python4ds/tidy-data.html) (Skim)
- [P4DS: CH14 Graphics for Communication](https://aeturrell.github.io/python4DS/communicate-plots.html) (Skim)
- [P4DS: CH16 Numbers](https://aeturrell.github.io/python4DS/numbers.html) (Read)
- [P4DS: CH17 Strings and Text](https://aeturrell.github.io/python4DS/strings.html) (Read)
- [P4DS: Ch18 Regular Expressions](https://aeturrell.github.io/python4DS/regex.html) (Read)
- [P4DS: CH19 Categorical Data](https://aeturrell.github.io/python4DS/categorical-data.html) (Read)

#### Optional References

- [Why to not use get_dummies](https://digestize.medium.com/why-is-using-get-dummies-a-bad-idea-for-your-ml-project-bcfd2683d2e4)


### Questions and Tasks (Core)

1. __Shorten the column names and clean them up for easier use with pandas.__ Provide a table or list that exemplifies how you fixed the names.  

1. __Clean and format the data so that it can be used in a machine learning model.__ As you format the data, you should complete each item listed below. In your final report provide example(s) of the reformatted data with a short description of the changes made.  

    a. Filter the dataset to respondents that have seen at least one film  
    a. Create a new column that converts the age ranges to a single number. Drop the age range categorical column  
    a. Create a new column that converts the education groupings to a single number. Drop the school categorical column  
    a. Create a new column that converts the income ranges to a single number. Drop the income range categorical column  
    a. Create your target (also known as “y” or “label”) column based on the new income range column  
    a. One-hot encode all remaining categorical columns  

1. __Validate that the data provided on GitHub lines up with the article by recreating 2 of the visuals from the article.__  

1. __Build a machine learning model that predicts whether a person makes more than $50k. Describe your model and report the accuracy.__


### Questions and Tasks (Stretch)

Here is an example Stretch question(s) for this project. Your instructor may assign different Stretch question(s). You must comment in Canvas when submitting your project if you completed any of the Stretch questions.  

1. __Build a machine learning model that predicts whether a person makes more than $50k. With accuracy of at least 65%. Describe your model and report the accuracy.__

1. __Validate the data provided on GitHub lines up with the article by recreating a 3rd visual from the article.__

1. __Create a new colum that converts the location groupings to a single number. Drop the location categorical column.__


### Submission:
::: {.callout-note collapse="true"}
When you have completed the report, you will need to follow this process to submit your work:

1. Have the Course Work Portfolio open in VS Code and open `Projects/Project0.qmd`
1. Click `Preview Button` in VS Code in the top right of the screen
    a. This will render the project but also entire course work portfolio into `HTML` files for review
    b. Confirm everything displas as you would like it to
    c. How you see it will be how it is viewed for grading
    d. If there is an error in any cell of the quarto files, the rendering will stop and you will need to fix the error before rendering again (if you get stuck post your error in Slack)
1. Once the report is confirmed close the preview and open the `GitHub Desktop` application
1. Confirm you are in the correct repository in the top left corner of the screen
1. Confirm you are on the correct branch `Main` in the top left corner of the screen (Never change off the `Main` branch)
1. Type a summary of the changes in the `Summary` box
1. Click `Commit to main` blue button in the bottom left corner
1. Click `Push origin` blue button in the middle right of the screen
    a. This will push all your changes in the project .qmd file to GitHub
    b. The publish.yml file will kick off an automated process to render the project into HTML files
    c. The HTML files will be published to GitHub pages in the gh-pages branch
    d. The URL to the published project will be in the deployment section in GitHub
        1. In `GitHub Desktop` click `Open in GitHub` to navigete to the repository
        2. Click on the `Actions` tab and make sure there were no errors in the rendering process
        3. Click on the `deployment` section of the main page of the repository to find the URL
        4. Navigate to the URL and confirm it displays as you intended
        5. Copy the URL and submit it in Canvas
:::

### Deliverables:

_Use this [template](../Templates/ds250_project_template.qmd) to submit your Client Report. The template has two sections:_

1. _A short elevator pitch that highlights key values or metrics from the results. Describing these key insights to interest or hook the reader to want to read more about your work. The writing style should be more technical with some creative elements. Do not summarize what you did._  
1. _Answers to the questions | tasks. Each should include a written description of your results, code cells with comments, charts and/or tables._  
1. _A short __summary of work must__ be submitted in the comments in Canvas wwhen you submit the URL. Rate your own work on a scale of 1-5. 1 being poor and 5 being excellent. Include a short description of why you rated your work the way you did._

