---
title: "Project 4: Can You Predict That?"
date: 2020-05-01T11:02:05+06:00
lastmod: 2020-09-15T10:42:26+06:00
weight: 5
draft: false
# search related keywords
keywords: [""]
---


### Walkthrough
```{=html}
<iframe id="kaltura_player" src="https://cdnapisec.kaltura.com/p/1157612/sp/115761200/embedIframeJs/uiconf_id/41338032/partner_id/1157612?iframeembed=true&playerId=kaltura_player&entry_id=1_ntkyl8mv&flashvars[localizationCode]=en&amp;flashvars[sideBarContainer.plugin]=true&amp;flashvars[sideBarContainer.position]=left&amp;flashvars[sideBarContainer.clickToClose]=true&amp;flashvars[chapters.plugin]=true&amp;flashvars[chapters.layout]=vertical&amp;flashvars[chapters.thumbnailRotator]=false&amp;flashvars[streamSelector.plugin]=true&amp;flashvars[EmbedPlayer.SpinnerTarget]=videoHolder&amp;flashvars[dualScreen.plugin]=true&amp;flashvars[Kaltura.addCrossoriginToIframe]=true&amp;&wid=1_tn9ykfrp" width="608" height="402" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="W08 - Project 4 Walkthrough"></iframe>
```


### Background

The clean air act of 1970 was the beginning of the end for the use of asbestos in home building.  By 1976, the U.S. Environmental Protection Agency (EPA) was given authority to restrict the use of asbestos in paint. Homes built during and before this period are known to have materials with asbestos You can [read more about this ban](https://www.asbestos.com/mesothelioma-lawyer/legislation/ban/).  

The state of Colorado has a large portion of their residential dwelling data that is missing the year built and they would like you to build a predictive model that can __classify__ if a house is built pre 1980.  

Colorado gave you home sales data for the city of Denver from 2013 on which to train your model. They said all the column names should be descriptive enough for your modeling and that they would like you to use the latest machine learning methods.


### Client Request

The Client is a state agency in Colorado that is responsible for the health and safety of its residents. They have a large portion of their residential dwelling data that is missing the year built and they would like you to build a predictive model that can classify if a house is built pre 1980.


### Data

__URL:__  [dwellings_ml.csv (ml ready)](https://github.com/byuidatascience/data4dwellings/raw/master/data-raw/dwellings_ml/dwellings_ml.csv)  
__Optional URL:__  [dwellings_neighborhoods_ml.csv (ml ready)](https://github.com/byuidatascience/data4dwellings/raw/master/data-raw/dwellings_neighborhoods_ml/dwellings_neighborhoods_ml.csv)  
__Informational URL:__  [dwellings_denver.csv (not cleansed)](https://github.com/byuidatascience/data4dwellings/raw/master/data-raw/dwellings_denver/dwellings_denver.csv)  
__Information:__ [Data description](https://github.com/byuidatascience/data4dwellings/blob/master/data.md)  


### Readings

- [Machine Learning Introduction](/Course%20Materials/ml.qmd) (Skim)
- [A visual introduction to machine learning](http://www.r2d3.us/visual-intro-to-machine-learning-part-1/) (Read)
- [P4DS: CH22 Joins](https://aeturrell.github.io/python4DS/joins.html) (Read)
- [How to choose a good evaluation metric for your Machine learning model](https://web.archive.org/web/20240213170741/https://ranvir.xyz/blog/how-to-evaluate-your-machine-learning-model-like-a-pro-metrics/) (Skim)


#### Optional References

- [Decision Tree Classification in Python](https://www.datacamp.com/community/tutorials/decision-tree-classification-python)    
- [Boosted algorithms in scikit-learn](https://scikit-learn.org/stable/modules/ensemble.html#gradient-tree-boosting)
- [scikit-plot package](https://github.com/reiinakano/scikit-plot)  
 

### Questions and Tasks (Core)

1. __Create 2-3 charts that evaluate potential relationships between the home variables and `before1980`.__ Explain what you learn from the charts that could help a machine learning algorithm.  

1. __Build a classification model labeling houses as being built “before 1980” or “during or after 1980”.__ Your goal is to reach or exceed 90% accuracy. Explain your final model choice (algorithm, tuning parameters, etc) and describe what other models you tried.  

1. __Justify your classification model by discussing the most important features selected by your model.__ This discussion should include a feature importance chart and a description of the features.  

1. __Describe the quality of your classification model using 2-3 different evaluation metrics.__ You also need to explain how to interpret each of the evaluation metrics you use.  


### Questions and Tasks (Stretch)

Here is an example Stretch question(s) for this project. Your instructor may assign different Stretch question(s). You must comment in Canvas when submitting your project if you completed any of the Stretch questions.  

1. __Repeat the classification model using 3 different algorithms.__ Display their Feature Importance, and Decision Matrix. Explian the differences between the models and which one you would recommend to the Client.  

1. __Join the `dwellings_neighborhoods_ml.csv` data to the `dwelling_ml.csv` on the `parcel` column to create a new dataset. Duplicate the code for the stretch question above and update it to use this data.__ Explain the differences and if this changes the model you recomend to the Client.  

1. __Can you build a model that predicts the year a house was built?__ Explain the model and the evaluation metrics you would use to determine if the model is good.


### Submission:
::: {.callout-note collapse="true"}
When you have completed the report, you will need to follow this process to submit your work:

1. Have the Course Work Portfolio open in VS Code and open `Projects/Project0.qmd`
1. Click `Preview Button` in VS Code in the top right of the screen
    a. This will render the project but also entire course work portfolio into `HTML` files for review
    b. Confirm everything displas as you would like it to
    c. How you see it will be how it is viewed for grading
    d. If there is an error in any cell of the quarto files, the rendering will stop and you will need to fix the error before rendering again (if you get stuck post your error in Slack)
1. Once the report is confirmed close the preview and open the `GitHub Desktop` application
1. Confirm you are in the correct repository in the top left corner of the screen
1. Confirm you are on the correct branch `Main` in the top left corner of the screen (Never change off the `Main` branch)
1. Type a summary of the changes in the `Summary` box
1. Click `Commit to main` blue button in the bottom left corner
1. Click `Push origin` blue button in the middle right of the screen
    a. This will push all your changes in the project .qmd file to GitHub
    b. The publish.yml file will kick off an automated process to render the project into HTML files
    c. The HTML files will be published to GitHub pages in the gh-pages branch
    d. The URL to the published project will be in the deployment section in GitHub
        1. In `GitHub Desktop` click `Open in GitHub` to navigete to the repository
        2. Click on the `Actions` tab and make sure there were no errors in the rendering process
        3. Click on the `deployment` section of the main page of the repository to find the URL
        4. Navigate to the URL and confirm it displays as you intended
        5. Copy the URL and submit it in Canvas
:::


### Deliverables:

_Use this [template](../Templates/ds250_project_template.qmd) to submit your Client Report. The template has two sections:_

1. _A short elevator pitch that highlights key values or metrics from the results. Describing these key insights to interest or hook the reader to want to read more about your work. The writing style should be more technical with some creative elements. Do not summarize what you did._  
1. _Answers to the questions | tasks. Each should include a written description of your results, code cells with comments, charts and/or tables._  
1. _A short __summary of work must__ be submitted in the comments in Canvas wwhen you submit the URL. Rate your own work on a scale of 1-5. 1 being poor and 5 being excellent. Include a short description of why you rated your work the way you did._
