---
title: "Project 6: Git Your DS Portfolio Online"
date: 2020-05-01T11:02:05+06:00
lastmod: 2020-09-15T10:42:26+06:00
weight: 6
draft: false
# search related keywords
keywords: [""]
---


### Walkthrough
```{=html}
<iframe id="kaltura_player" src="https://cdnapisec.kaltura.com/p/1157612/sp/115761200/embedIframeJs/uiconf_id/41338032/partner_id/1157612?iframeembed=true&playerId=kaltura_player&entry_id=1_4ib8sif3&flashvars[localizationCode]=en&amp;flashvars[sideBarContainer.plugin]=true&amp;flashvars[sideBarContainer.position]=left&amp;flashvars[sideBarContainer.clickToClose]=true&amp;flashvars[chapters.plugin]=true&amp;flashvars[chapters.layout]=vertical&amp;flashvars[chapters.thumbnailRotator]=false&amp;flashvars[streamSelector.plugin]=true&amp;flashvars[EmbedPlayer.SpinnerTarget]=videoHolder&amp;flashvars[dualScreen.plugin]=true&amp;flashvars[Kaltura.addCrossoriginToIframe]=true&amp;&wid=1_my754v8t" width="608" height="402" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="W12 - Project 6 Walkthrough"></iframe>
```

### Background

GitHub is an online platform where data scientists and developers can communicate and share work. It has also morphed into a tool to house all your work in a portfolio. Think about an Art student and how they have to develop their portfolio of various skills they have across the art classes. Similarly you will want to showcase you skillset across the Data Science skillsets. 

As students, you will want to curate your creative work on GitHub using a program called Git. GitHub is the place to share your original work, **not your homework assignments**. The reading assignments will dive deaper into what to include in your portfolio and what not to include.

Many people store their personal websites, blogs, and project websites on GitHub.  Our textbook and course are hosted on GitHub, and you can see [J. Hathaway's](http://jhathaway.io/) or [Ryan Hafen's](https://ryanhafen.com/) personal Data Science websites that are hosted on GitHub as well. 

For this project, you will be making a public website that is a data science portfolio that will be hosted on GitHub. Your Resume (from project 0) will be one section of your portfolio/website. You should also post Data Science Society projects, personal projects, and any other data science related work you have done outside of class.

### Data
__Portfolio:__ [BYUI Data Science Portfolio](https://github.com/byuidatascience/datascience_portfolio)

### Readings

- [Git and Github for DS](../Setup/git_github_setup.qmd)
- [Pull and Merge Forks on Github](../Course%20Materials/git_pull_merge.qmd)
- [New to Git and GitHub? This Essential Beginners Guide is for you](https://www.analyticsvidhya.com/blog/2020/05/git-github-essential-guide-beginners/)
- [Git vs. GitHub: What is the difference between them?](https://www.theserverside.com/video/Git-vs-GitHub-What-is-the-difference-between-them#:~:text=The%20key%20difference%20between%20Git,and%20upload%20or%20download%20resources.)
- [Using Version Control in VS Code](https://code.visualstudio.com/docs/editor/versioncontrol)
- [Git in Visual Studio Code video](https://www.youtube.com/watch?v=wMqukSKYcvU)

### Portfolio Resources

- [How to Modify a Quarto Website](https://quarto.org/docs/websites/website-tools.html)
- [How to Create a Compelling Github Portfolio](https://towardsdatascience.com/how-to-create-a-compelling-github-portfolio-a229e7472a92)
- [How to Create a Professional Portfolio on Github](https://towardsdatascience.com/how-to-create-a-professional-portfolio-on-github-that-will-help-land-your-first-job-in-data-science-e1fc8bd7a797)
- [Data Science Portfolios That Will Get You the Job](https://www.dataquest.io/blog/build-a-data-science-portfolio/)
- [4 Data Science Portfolio Projects You Need to Create](https://builtin.com/data-science/data-science-portfolio-projects)
- [Example 1 - Data Science Portfolio](https://github.com/rodrigo-arenas/portfolio)
- [Example 2 - Data Science Portfolio](https://github.com/topics/portfolio-website)

### Questions and Tasks

1. __Git a Data Science Portfolio in Ghithub (main page)__
    a. __Use the Portfolio Template on your Githhub root directory__
        * __Navigate to the [Data Science Portfolio](https://github.com/byuidatascience/datascience_portfolio) in GitHub.__
        * __Click the Green Button `Use this template` and select `Create a new repository`__
        * __Select yourself as the `Owner`__
        * __Name the repository as `username.github.io` where the username is your username on GitHub (Note: If the first part of the repository doesn’t exactly match your username, it won’t work, so make sure to get it right.)__
        * __Click the Green Button `Create repository`__

    a. __Create a new branch `gh-pages`__
        * __Click the `Branch: main` button then `view all branches`__
        * __Click the `New Branch` button__
        * __Name the branch `gh-pages` and click the Green Button `Create new branch`__

    a.  __Modify Pages Settings for Build and deployment from `main` to `gh-pages`:__
        * __Click the `Settings` tab__
        * __Scroll down to the `Pages` section in the left hand menu__
        * __Locate the Build and deployment section and change Branch from `main` to `gh-pages`__

    a.  __Clone the repository to your computer__
        * __Click the `Code` tab__
        * __Click the Green Button `Code` and select `Open with GitHub Desktop`__
        * __Click the Green Button `Open in Visual Studio Code`__

    a.  __Update the `_quarto.yml` file__
        * __Change the `title` to your name__
        * __Change the `repo-rul` to a brief description of your portfolio__
        * __Change the page-footer `left:` to your name__
        * __Change the page footer `href:` to your LinkedIn profile link__
        * __Scroll to the bottom and change the theme `light:` and/or `dark:` to another theme (optional)__

    a.  __Push the changes to GitHub via Github Desktop__
        * __Make sure your current repo in the top left is `username.github.io`__
        * __Type a commit message and click the Blue Button `Commit to main`__
        * __Click the Blue Button `Push origin`__

    a.  __Confirm the Github Actions are working__
        * __Navigate to the repo in GitHub and click on the  `Actions` tab__
        * __Confirm the `Update _quarto.yml` is working by the yellow circle turning to a green check circle (Note: this can take 3-5min)__

1. __Git your Resume in your Portfolio__
    * __Move your resume from Project 0 into the Portfolio by replacing the `resume.qmd` file__
    * __Push your results to GitHub with GitHub Desktop.__  

### Deliverables:

1. _Complete the questions_  
1. _Submit a URL link to your portfolio._  