---
title: "Project 6: Git your resume online"
date: 2020-05-01T11:02:05+06:00
lastmod: 2020-09-15T10:42:26+06:00
weight: 6
draft: false
# search related keywords
keywords: [""]
---

### Background

GitHub is an online platform where data scientists and developers can communicate and share work. As students, you will want to curate your creative work on GitHub using a program called Git. GitHub is the place to share your original work, not your homework assignments.  

Many people store their personal websites, blogs, and project websites on GitHub.  Our textbook and course are hosted on GitHub, and you can see [J. Hathaway's](http://jhathaway.io/) or [Ryan Hafen's](https://ryanhafen.com/) personal Data Science websites that are hosted on GitHub as well. For this project, you will be making a public resume that will be hosted on GitHub.

During this project you will learn the process of Git and the tools of GitHub. We will use Git to have others in our class to edit your resume.  Take the process seriously (pick a suitable username and write a good resume), and you will have the beginning of your social presence in the DS/CS space. 

### Data

__Repository:__ [Markdown Resume (mdresume) Repository](https://github.com/byuids-resumes/mdresume)   
__Information:__ [BYUI Data Science Resumes](https://github.com/byuids-resumes)


### Readings

- [New to Git and GitHub? This Essential Beginners Guide is for you](https://www.analyticsvidhya.com/blog/2020/05/git-github-essential-guide-beginners/)
- [Git vs. GitHub: What is the difference between them?](https://www.theserverside.com/video/Git-vs-GitHub-What-is-the-difference-between-them#:~:text=The%20key%20difference%20between%20Git,and%20upload%20or%20download%20resources.)
- [Using Version Control in VS Code](https://code.visualstudio.com/docs/editor/versioncontrol)
- [Git in Visual Studio Code video](https://www.youtube.com/watch?v=wMqukSKYcvU)



<!-- http://www.cs.cornell.edu/courses/cs4411/2020sp/schedule/slides/02-Git.pdf -->

### Questions and Tasks

1. [Join GitHub](https://github.com/join). Pick a username you would be ok sharing with a potential employer.
1. __Join the [BYUI Data Science Resumes](https://github.com/byuids-resumes) GitHub organization and use the template repository to make a resume repository  under your own GitHub account. A good name might be “Lastname-Resume”__
1. __Clone your repository to your computer and build a first draft of your resume.__
1. __Push your results to GitHub and have another student fork your repository to make edits.__
1. __Accept the proposed changes from the student review and finish your final version.__
1. __After your resume is complete, make sure your it is forked into [BYU-I Data Science Resumes](https://github.com/byuids-resumes)__

### Deliverables:

1. _Complete the questions_
1. _Submit a URL link to your repo within the byuids-resumes group._

