---
title: "Frequently Asked Questions"
date: 2020-05-01T11:02:05+06:00
lastmod: 2020-09-15T10:42:26+06:00
draft: false
---

### "What do you mean by data science programming?"
Most likely, you have had 1-2 courses of programming before you have taken DS 250.  Unlike traditional computer science courses, DS 250 uses Python in an interactive mode instead of building programs. The data provider usually has some big questions that need answering; However, there are hundreds of little issues and responses along the way.  We use programming to facilitate this investigation.  

There are similarities with User Experience Designers.  In our case, we don't get to ask users about their experience.  We use programming to ask data about its background, and each data set has its own history.  We want our analysis to mold to that experience. You can think of data science programming like a first date with your data. You can't write one long program nieve of the issues and nuances each living data set provides. 

---

### "How does DS 250 compare to DS 350?"

The two courses have similarities.  You could think of DS 250 as an introduction to data wrangling and visualization.  Both classes use real-world data and are built around data science projects.  There are some critical differences between the two courses. 

- In this course, we use Python, and DS 350 uses R. 
- We are introducing the principles of data science programming in DS 250.
- The course is only 2-credits.
- DS 250 is intended to introduce visualization, wrangling, and modeling.

---

### faq "How does DS 250 prepare me for DS 350 and CSE 450?"
You will be comfortable with interactive programming and have an introduction to the principles of data formats for data science applications.  You will be introduced to principles related to machine learning, data wrangling, and data visualization.

---

### "What programming languages do we use in this course?"
The course is done using Python.  We focus on the pandas and Altair packages.

---

### "What are the prerequisites for this course?"
Using the new courses at BYU-I, the prerequisite is CSE 110.  However, if you have experience programming from other classes, you most likely are prepared for this course.

---

### "Why Python instead of R?"
The computer science and software engineering programs at BYU-I use Python as their foundational courses.  The standard student will have some experience with Python before DS 250. Python is an essential programming language for data scientists, and we already have [DS350](https://byuistats.github.io/M335/), which is taught in R.  

---

### "What is pandas?"
[pandas](https://pandas.pydata.org/docs/getting_started/index.html) is the foundational data science package in Python. If you are using tabular data you will be in pandas.

---

### "Why are we using Altair instead of Seaborn or Matplotlib?"
Matplotlib was the first visualization package to gain a following in Python.  Seaborn is built on top of Matplotlib.  Many data scientists use both in their work—neither leverage the [grammar of graphics](https://www.amazon.com/Grammar-Graphics-Statistics-Computing/dp/0387245448) as developed by Leland Wilkinson. Altair is built on Vega-Lite, which uses the Vega visualization grammar. It is declarative and actively developed.  We expect that it will become the predominant visualization package in Python <https://youtu.be/FytuB8nFHPQ> and <https://youtu.be/vTingdk_pVM>.

---