---
title: "Course Setup"
---

### How to get your computer setup?

The left navigation bar is sequenced for the setup process:  

If you want to use a AWS Cloud Virtual Machine (VM) instead of your laptop and install Python and VS Code on that VM, start here:  

1. Create an [AWS EC2 VM](/Setup/aws_setup.qmd) (optional)  
 
This course uses Slack as our main tool for communication and collaboration.  You will need to install Slack on your laptop and mobile device.  You will also need to create a Slack account using your BYU-Idaho email. If you have an existing account, you can either change your email to the BYU-Idaho email or you can create a new account.

2. Install Slack on your laptop: 
    * [Windows](https://slack.com/downloads/windows)  
    * [Mac](https://slack.com/intl/en-in/downloads/mac)  
3. Install Slack on your Cell: 
    * [Android](https://slack.com/downloads/android)  
    * [iPhone](https://slack.com/downloads/ios)
4. Create a Slack Account using your BYU-Idaho email: 
    * [Slack](https://slack.com/get-started#/createnew) 

If you want to use Python and VS code on your own laptop, start here:  

5. Install [Python](/Setup/python_setup.qmd)
6. Install [Python Libraries](/Setup/python_lib.qmd)    
7. Install [VS Code](/Setup/vs_code_setup.qmd)  
8. Install [Quarto](/Setup/quarto_setup.qmd)  
9. Install [Git & GitHub](/Setup/git_github_setup.qmd) 
<!-- 1. Plotly Express Setup [Python](/Setup/plotly_setup.qmd)  -->
<!--1. Install Altair--> 

You will need to use SQL in Week 6:

10. [SQL](/Setup/sql_setup.qmd) setup and test

Using Copilot (AI)?

>Copilot is a micro-assistant that helps you write better code. It is a VS Code extension that uses AI built off Chat GPT-4. With your student GitHub account, you can use Copilot for free. It helps you write code faster and with fewer errors. It is not perfect, but it is a great tool to help you learn to code.

>This course is designed with a Core and Stretch for each project. It is expected that you acomplish the Core __**without**__ the use of Copilot. The Stretch is where you __**should**__ use Copilot. Without using Copilot, the stretch questions will be more challenging. The goal is to help you learn to code and to use Copilot as a tool to help you learn, not to do the work for you.

11. Install [GitHub Copilot](/Setup/copilot_setup.qmd) (required)

Prefer an Open Source AI tool try [Llama](https://ollama.com/library/codellama)?  

>Llama is an AI-powered code editor that helps you write better code. It is a VS Code extension that uses AI built off Chat GPT-4. With your student GitHub account, you can use Llama for free. It helps you write code faster and with fewer errors. It is not perfect either, but it is a great tool to help you learn to code.

12. Install [Llama](https://generativeai.pub/100-local-llama-coding-assistant-bye-bye-gpt-4-cbd2b507b822) (optional)
