---
title: "DS 250 Competency"
date: 2020-05-01T11:02:05+06:00
lastmod: 2020-09-15T10:42:26+06:00
weight: 1
draft: false
# search related keywords
keywords: [""]
---

> We need skills not grades!  [Shifting Attention](https://www.thegraidenetwork.com/blog-all/2018/8/1/retiring-the-red-pen-shifting-attention-from-grades-to-learning)

### Competency scale {#scale}

You must complete all competency items at the level detailed to achieve the listed grade. You can request half-step adjustments if you fall slightly short on some elements and over on others.  

You will need to provide a detailed description in your __**Course Goals Letter**__ of the items you completed to support your grade request.  If a student was in the B range they might write the following:  

> Example Course Goals Letter (End):  
I got three fives, one four, and two threes for 29 points on the projects. I met the checkpoint requirements with 4 full mark mid-project checkpoints and 4 methods and calculation checkpoints. I regularly attended data science society.  I believe my coding challenge will be above a 3.  I request a _B+_.  

::: {.panel-tabset}

## Leader (A)
#### Leader (A)
| Element                                   | Requirement     | Description               |
| :----------------------------------       | --------------- | ------------------------- |
| __Projects__                              | 34 Points       | 5 points per project      |
| __Project Stretchs__                      | At least 3      | --                        |
| __Mid-project checkpoints__               | 5 completed     | Full credit (online only) |
| __Methods & Calculations checkpoints__    | 6 completed     | 100% unlimited attempts   |
| __DS Community__                          | At least 3      | --                        |
| __Course Goal Letter (End)__              | submission      | --                        |
| __Coding challenge__                      | At least 3      | Score is out of 4         |

## Supporter (B)
#### Supporter (B)
| Element                                   | Requirement     | Description               |
| :----------------------------------       | --------------- | ------------------------- |
| __Projects__                              | 29 Points       | 5 points per project      |
| __Project Stretchs__                      | At least 2      | --                        |
| __Mid-project checkpoints__               | 3 completed     | Full credit (online only) |
| __Methods & Calculations checkpoints__    | 5 completed     | 100% unlimited attempts   |
| __DS Community__                          | At least 2      | --                        |
| __Course Goal Letter (End)__              | submission      | --                        |
| __Coding challenge__                      | At least 3      | Score is out of 4         |

## Listener (C)
#### Listener (C)
| Element                                   | Requirement     | Description               |
| :----------------------------------       | --------------- | ------------------------- |
| __Projects__                              | 24 Points       | 5 points per project      |
| __Project Stretchs__                      | At least 1      | --                        |
| __Mid-project checkpoints__               | 3 completed     | Full credit (online only) |
| __Methods & Calculations checkpoints__    | 3 completed     | 100% unlimited attempts   |
| __DS Community__                          | At least 1      | --                        |
| __Course Goal Letter (End)__              | submission      | --                        |
| __Coding challenge__                      | At least 2      | Score is out of 4         |

## Asleep (D)
#### Asleep (D)
| Element                                   | Requirement     | Description               |
| :----------------------------------       | --------------- | ------------------------- |
| __Projects__                              | 14 Points       | 5 points per project      |
| __Project Stretchs__                      | None            | --                        |
| __Mid-project checkpoints__               | 1 completed     | Full credit (online only) |
| __Methods & Calculations checkpoints__    | 2 completed     | 100% unlimited attempts   |
| __DS Community__                          | None            | --                        |
| __Course Goal Letter (End)__              | None            | --                        |
| __Coding challenge__                      | None            | Score is out of 4         |

:::


### Competency elements {#elements}


::: {.panel-tabset}
## Projects
#### Projects (Questions|Tasks)

_Each of the seven projects is worth 5 points. There is a draft submission due Wednesday (W) of the 2nd week of the project and the final draft due the following Saturday (S). This gives you two attempts to get full points on the project. There are 6 two-week projects (P0-P5) and 1 one-week project (P6)._

##### Grading Details

* **1 point:**  Submission
* **3 points:** Submission of a good faith attempt with a statement of work quality.
* **4 points:** High-quality work that addresses each of the __**Questions and Tasks**__ and a comment in Canvas of your statement of work quality.
* **5 points:** Addressed issues and completion of resubmission (if needed).

## Quiz Checkpoints
#### Checkpoints (methods and calculations)

_These checkpoints are in Canvas and they open when the project starts.  They have unlimited attempts and remain open until the end of the semester._

##### Examples

* **Fact-Finding Questions (Calculate descriptive summaries):**  Fact-finding questions help you with calculations that build into the _Questions and Tasks_ of the project.  These questions have clearly defined answers using Python calculations.  You should expect 2-3 problems.

1. Example: Using the top 10 airports in size, what is the average size?
2. Example: What proportion of flights are delayed at the largest airport?

* **How the code works questions (Explaining the tools):**  This part could have direct answer questions or open-ended questions.  

1. Example (direct):  What is the recommended function for arranging your data by a variable? What are the outputs after using `<FUNCTION>`?
2. Example (open): Your client has shown some confusion about NumPy's 'nan' handling in Python. Help them understand by answering the question, 'How is missing data handled in Pandas?' 

## Checkpoints Mid-Project
#### Checkpoints (Mid-project status)

_The mid-project checkpoint has a few questions.  It opens the first day of the project and closes at 1 am on the 3rd day of class for the project. It has the following questions._

##### Examples

1. Have you checked off more than one grand question from the current project?  (Yes/No)
2. Have you spent at least 2 hours using code to tackle problems related to the case study? (Yes/No).
3. Have you prepared questions you have about the case study to ask in your next meeting? (Yes/No).

## DS Community
#### Data Science Community

To earn credit for the DS Community element you must __complete tasks from the list below__. At the end of the semester, you will be asked to report on which tasks you completed and what you learned from them. See the Competency Scale above to determine how many you need to complete based on the grade you want.

-  Attend [Data Science Society](https://byuidatascience.github.io/society/) at least once.
- Sign up for an email newsletter that will teach you more about data science. [Data Science Weekly](https://www.datascienceweekly.org/) or [Data Elixir](https://dataelixir.com/) are good options.
- Listen to a podcast episode about data science. [Build a Career in Data Science](https://podcast.bestbook.cool/) has some excellent episodes.
- Watch a professional presentation on YouTube about data science. Be prepared to share the link and a summary of the video.
- Reach out to someone who works in a data-related field and ask them for 15 minutes of their time. Use this time to conduct an "[informational interview](https://brightspotcdn.byu.edu/54/b6/2554ebb842fab54640a15ff0afb3/informational-interview.pdf)" and learn more about their responsibilities and career path.
- Research and apply to at least 5 data-related jobs or internships.

## Course Goals Letter
#### Finishing the semester

Submit a __**Course Goals Letter (End)**__ that includes what you have learned from this class, the next data science course you plan on taking, and the final grade that you are requesting based on the work you have submitted compared to the competencies above.

## Challenge
#### Coding challenge

We will have an in-class coding challenge on the ultimate or penultimate day of class. It would be best if you did not view this challenge like a traditional exam.  It will cover the general techniques that we have been practicing throughout the course.

We expect to have a few practice challenges throughout the semester. We will score the coding challenge on a four-point scale.

- **1 point:** At least you tried.
- **2 points:** You have learned some items from the course, but your work in the coding challenge is deficient.
- **3 points:** Your submission uses proper coding techniques and addresses the objective.
- **4 points:** Exceptional work.  Your code can be used as a solution to share with others.

:::
