---
title: "Python for Data Science"
date: 2020-05-01T11:02:05+06:00
lastmod: 2020-09-15T10:42:26+06:00
weight: 2
draft: false
# search related keywords
keywords: [""]
---

Python for Data Science [python4DS](https://aeturrell.github.io/python4DS/welcome.html) is a port of [R for Data Science (2e)](https://r4ds.hadley.nz/) into Python. The authors keep Garrett Grolemund and Hadley Wickham’s writing and examples as much as possible while demonstrating Python instead of R. The book focuses on [pandas](https://pandas.pydata.org/docs/user_guide/index.html#user-guide) and [LetsPlot](https://lets-plot.org/python/index.html) in the Python code snippets.

This book will teach you how to do data science with Python: You’ll learn how to get your data into Python, get it into the most useful structure, transform it, visualise it and model it. In this book, you will find a practicum of skills for data science. Just as a chemist learns how to clean test tubes and stock a lab, you’ll learn how to clean data and draw plots—and many other things besides. These are the skills that allow data science to happen, and here you will find the best practices for doing each of these things with Python. You’ll learn how to use the grammar of graphics, literate programming, and reproducible research to save time. You’ll also learn how to manage cognitive resources to facilitate discoveries when wrangling, visualising, and exploring data.


### Learn How to Setup Python
[Python](/Setup/python_setup.qmd) 