---
title: "Course Setup"
---

### How to get your computer setup?

The left navigation bar is sequenced for the setup process:  

If you want to use a AWS Cloud Virtual Machine (VM) instead of your laptop and install Python and VS Code on that VM, start here:  

1. Create an [AWS EC2 VM](/Setup/aws_setup.qmd) (optional)  
 
This course uses Slack as our main tool for communication and collaboration.  You will need to install Slack on your laptop and mobile device.  You will also need to create a Slack account using your BYU-Idaho email. If you have an existing account, you can either change your email to the BYU-Idaho email or you can create a new account.

1. Install Slack on your laptop: 
    * [Windows](https://slack.com/downloads/windows)  
    * [Mac](https://slack.com/intl/en-in/downloads/mac)  
1. Install Slack on your Cell: 
    * [Android](https://slack.com/downloads/android)  
    * [iPhone](https://slack.com/downloads/ios)
1. Create a Slack Account using your BYU-Idaho email: 
    * [Slack](https://slack.com/get-started#/createnew) 

If you want to use Python and VS code on your own laptop, start here:  

1. Install [Python](/Setup/python_setup.qmd)  
1. Install [VS Code](/Setup/vs_code_setup.qmd)  
1. Install [Quarto](/Setup/quarto_setup.qmd)  
1. Install [Python Libraries](Setup/python_lib.qmd)  
1. Install [Git](/Setup/git_github_setup.qmd)  
<!--1. Install Altair--> 

You will need to use SQL in Week 6:

1. [SQL](/Setup/sql_setup.qmd) setup and test

Interested in using Copilot all Semester?

1. Install [GitHub Copilot](/Setup/copilot_setup.qmd) (optional)
