---
title: "AWS Virtual Machine Setup"
date: 2020-05-01T11:02:05+06:00
lastmod: 2020-09-15T10:42:26+06:00
weight: 8
draft: false
# search related keywords
keywords: [""]
---


### Prerequisites
If you want to use a AWS Academy VM for this course, you will need to have an AWS Educate account. Please [email the admin](mailto:clarkty@byui.edu) for with the subject line "AWS Educate Account Request" and include your full name and course code. You will receive an email from AWS Educate with instructions on how to create an account.


### AWS Virtual Machine Setup
Watch and follow the two videos, and or follow along with the AWS Virtual Machine Creation Document. Copy paste code from the cell below.

```{=html}
<iframe width="560" height="315" src="https://www.youtube.com/embed/H59S0YBOv4A?si=w4pHoAboHN-t8YNl" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
```

```{=html}
<iframe width="560" height="315" src="https://www.youtube.com/embed/4ia0cvfgSrY?si=UReGJTVcf4SeMFW9" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
```


### Setup AWS Documentation
- [AWS Virtual Machine Creation](https://www.cse-byui.org/)


### Copy Paste Code Block
```{.batch}
git clone https://github.com/byui-bwh/db-workstation-automation.git 

cd db-workstation-automation/

. ./provision_vm.sh
```

### Clone this GitHub Repository
```{.batch}
cd Desktop
git clone https://github.com/NicholasBoss/clarkstudents24.git
```

### Installing GitHub Desktop
- Open the Repo just cloned in Visual Studio Code
- Navigate through `code` to `week 2` and open the `root.py` file
- Run the code in the `root.py` file by pressing the play button in the top right corner of the file
    - When asked to run the GitHub desktop script answer `y`
    - When asked to run the file setup script answer `n`
    - Close the file

### Installing Quarto CLI
- Navigete to the Quarto CLI [website for Linux](https://byuidss.slack.com/archives/D01ULMRAD8T/p1715879012282849)
    - Run all the termainal commands on the site in the terminal in the AWS instance

### Installing the Quarto VS Code Extension
- Open Visual Studio Code
- Click on the `Extensions` icon in the left side bar
- Search for `Quarto` in the search bar
- Click the `Install` button on the `Quarto` extension
- Close the `Extensions` tab

### Install Python Libraries
- Open the terminal in Visual Studio Code
- Run the following command to install the required Python libraries  

```{.batch}
pip install numpy pandas scikit-learn plotly.express nbformat nbclient pyyaml jupyter
```

### Install Other VS Code Extensions
- [Jupyter](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter)
- [Live Share](https://marketplace.visualstudio.com/items?itemName=MS-vsliveshare.vsliveshare)
- [Python](https://marketplace.visualstudio.com/items?itemName=ms-python.python)
- [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.python)