---
title: "Git and GitHub for DS"
date: 2020-05-01T11:02:05+06:00
lastmod: 2020-09-15T10:42:26+06:00
weight: 8
draft: false
# search related keywords
keywords: [""]
---

### Setup Git and Github 
##### Github will be used for publishing all projects

1. Install [git](https://git-scm.com/) on your computer   
    * [Windows](https://git-scm.com/download/win) Installation  
    * [Mac](https://git-scm.com/download/mac) Installation  
        Note: Mac users can install git using [homebrew](https://brew.sh/) by running `brew install git` in the terminal. You will need to install [homebrew](https://brew.sh/) first if you don't have it  

1. Create a [GitHub](https://education.github.com/discount_requests/application) Student Account with your BYUI-I email. 
    * Use an [appropriate username](https://workplace.stackexchange.com/questions/83967/does-my-employer-care-about-my-github-username). It will be the name of your public profile and website in Project 6.  

1. [Install](https://desktop.github.com/) GitHub Desktop

1. Connect to our BYU-I organizations on Github (optional)  
    * [BYU-I Data Science Society](https://posit.byua. edu/connect/#/apps/ef78adcd-d72b-4e3f-ac45-3e5e662fbd73/access) _default organization_  

1. __Git a Course Work Portfolio in Ghithub__
    a.  __Use the Portfolio Template on your Githhub root directory__
        * __Navigate to the [Course Work Portfolio](https://github.com/byuidatascience/course_work_portfolio) in GitHub.__
        * __Click the Green Button `Use this template` and select `Create a new repository`__
        * __Select `byuids` as the `Owner`(you should have been added by your teacher if you dont see byuids ask them to add you)__
        * __Name the repository as `your name`__
        * __Click the Green Button `Create repository`__

    a.  __Create a new branch `gh-pages`__
        * __Click the `Branch: main` button then `view all branches`__
        * __Click the `New Branch` button__
        * __Name the branch `gh-pages` and click the Green Button `Create new branch`__

    a.  __Modify Pages Settings for Build and deployment from `main` to `gh-pages`:__
        * __Click the `Settings` tab__
        * __Scroll down to the `Pages` section in the left hand menu__
        * __Locate the Build and deployment section and change Branch from `main` to `gh-pages`__

    a.  __Clone the repository to your computer__
        * __Click the `Code` tab__
        * __Click the Green Button `Code` and select `Open with GitHub Desktop`__
        * __Click the Green Button `Open in Visual Studio Code`__

    a.  __Update the `_quarto.yml` file__
        * __Change the `title` to your name__
        * __Change the `repo-rul` to a brief description of your portfolio__
        * __Change the page-footer `left:` to your name__
        * __Change the page footer `href:` to your LinkedIn profile link__
        * __Scroll to the bottom and change the theme `light:` and/or `dark:` to another theme (optional)__

    a.  __Push the changes to GitHub via Github Desktop__
        * __Make sure your current repo in the top left is `username.github.io`__
        * __Type a commit message and click the Blue Button `Commit to main`__
        * __Click the Blue Button `Push origin`__

    a.  __Confirm the Github Actions are working__
        * __Navigate to the repo in GitHub and click on the  `Actions` tab__
        * __Confirm the `Update _quarto.yml` is working by the yellow circle turning to a green check circle (Note: this can take 3-5min)__

1. __Git your Resume in your Portfolio (Learn Markdown)__
    * __Edit the `resume.qmd` file in the Course Work Portfolio use markdown to to populate your resuem__
    * __Push your results to GitHub with GitHub Desktop.__  